version: 2.1

jobs:

  # Perform style checking
  lint:
    docker:
      - image: cimg/node:16.8

    working_directory: ~/app

    steps:
      - checkout

      # Restore cached dependencies
      - restore_cache:
          key: dependency-cache-v1-{{ checksum "package.json" }}

      # Install dependencies
      - run:
          name: Installing dependencies
          command: npm install

      # Lint the files
      - run:
          name: 'Lint'
          command: npm run lint

      - save_cache:
          key: dependency-cache-v1-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ./package-lock.json

  # Build the app
  build:
    docker:
      - image: cimg/node:16.8

    working_directory: ~/app

    steps:
      - checkout

      # Restore cached dependencies
      - restore_cache:
          key: dependency-cache-v1-{{ checksum "package.json" }}

      # Install dependencies
      - run:
          name: Installing dependencies
          command: npm install

      # Build for production
      - run:
          name: Build
          command: npm run build

      - save_cache:
          key: dependency-cache-v1-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ./package-lock.json

      - persist_to_workspace:
          root: ~/app
          paths:
            - dist/*

workflows:

  # Lint and build
  lint-build:
    jobs:
      - lint:
          name: Lint
      - build:
          name: Build
          requires:
            - Lint
